//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attack
    {
        public long CityID { get; set; }
        public long ShipID { get; set; }
        public long TargetID { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
    }
}
