//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildType
    {
        public BuildType()
        {
            this.Building = new HashSet<Building>();
            this.Building1 = new HashSet<Building>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Building> Building { get; set; }
        public virtual ICollection<Building> Building1 { get; set; }
    }
}
