//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Attack = new HashSet<Attack>();
            this.Attack1 = new HashSet<Attack>();
            this.Attack2 = new HashSet<Attack>();
            this.Inhabitant1 = new HashSet<Inhabitant>();
            this.Ship = new HashSet<Ship>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CityNameID { get; set; }
        public long Inhabitant { get; set; }
        public decimal Gold { get; set; }
        public long Food { get; set; }
        public long Mead { get; set; }
        public long Equipment { get; set; }
        public long Prisoner { get; set; }
    
        public virtual ICollection<Attack> Attack { get; set; }
        public virtual ICollection<Attack> Attack1 { get; set; }
        public virtual ICollection<Attack> Attack2 { get; set; }
        public virtual CityName CityName { get; set; }
        public virtual ICollection<Inhabitant> Inhabitant1 { get; set; }
        public virtual ICollection<Ship> Ship { get; set; }
    }
}
