//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityName
    {
        public CityName()
        {
            this.City = new HashSet<City>();
            this.Target = new HashSet<Target>();
            this.Target1 = new HashSet<Target>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<Target> Target { get; set; }
        public virtual ICollection<Target> Target1 { get; set; }
    }
}
