//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inhabitant
    {
        public Inhabitant()
        {
            this.Soldier = new HashSet<Soldier>();
        }
    
        public long ID { get; set; }
        public long CityID { get; set; }
        public string Name { get; set; }
        public long Hp { get; set; }
        public long Strength { get; set; }
        public long Endurance { get; set; }
        public long Morale { get; set; }
        public long Leadership { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Soldier> Soldier { get; set; }
    }
}
