//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class InhabitantType
    {
        public InhabitantType()
        {
            this.Inhabitant = new HashSet<Inhabitant>();
        }
    
        public long ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Inhabitant> Inhabitant { get; set; }
    }
}
