//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public long ID { get; set; }
        public long Level { get; set; }
        public long Hp { get; set; }
        public decimal Price { get; set; }
        public long CityID { get; set; }
    
        public virtual City City { get; set; }
    }
}
