//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public long ID { get; set; }
        public long CityNameID { get; set; }
        public decimal Gold { get; set; }
        public long Army { get; set; }
        public long Distance { get; set; }
        public long CityID { get; set; }
    
        public virtual CityName CityName { get; set; }
        public virtual CityName CityName1 { get; set; }
    }
}
