//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VikingManagerDBEntities : DbContext
    {
        public VikingManagerDBEntities()
            : base("name=VikingManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Building> Building { get; set; }
        public DbSet<BuildType> BuildType { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<CityName> CityName { get; set; }
        public DbSet<Inhabitant> Inhabitant { get; set; }
        public DbSet<Ship> Ship { get; set; }
        public DbSet<Soldier> Soldier { get; set; }
        public DbSet<Target> Target { get; set; }
        public DbSet<Attack> Attack { get; set; }
        public DbSet<InhabitantType> InhabitantType { get; set; }
    }
}
